### ISSUE TITLE
Query Module not working?

### ISSUE THREAD

**Issue by cyberfreaq** [knavesec/Max#13]
Hi,

when I run `python3 max.py get-info --kerb` I get a list of kerberoastable users.
However, running the pre-built BloodHound query "List all Kerberoastable Accounts" with `python3 max.py query "MATCH (n:User) WHERE n.hasspn=true RETURN n"` shows no results. The same holds true for all other Cypher queries I tried.

Do you have any idea why this happens?
Is there an easy way to troubleshoot this issue (error logs, etc.)?

**Comment by knavesec** [comment]
Hey @cyberfreaq 

The query module is working properly, the issue is in your query! The pre-built BH queries are intended to return full nodes `(n)` where the query module is meant to return specific properties like `n.name`. If you run the same query and return `n.name` or any other property it works fine, see bullet 2 of the `query` wiki notes. Also I will note that this did help me find an unrelated bug in the code, so thanks!

**Comment by cyberfreaq** [comment]
Thanks for your fast reply!!
