### ISSUE TITLE
Strange Python Error When Enumerating Known Groups

### ISSUE THREAD

**Issue by jsarkisian** [knavesec/Max#2]
**Problem: The following command:**

`python3 max.py -u neo4j -p pass --url http://127.0.0.1:7474 get-info --group-members "REMOTE DESKTOP USERS"`

**Returns the following error:**

`Traceback (most recent call last):
  File "max.py", line 650, in <module>
    main()
  File "max.py", line 622, in main
    get_info(args)
  File "max.py", line 235, in get_info
    query = query.format(enabled="")
KeyError: 'name'
`

This happens regardless of the groups I try, all of which I have confirmed exist.

Thanks!

**Comment by knavesec** [comment]
Hey @jsarkisian -

Couple things to note: firstly to use that function you'll need to provide the full group name `"REMOTE DESKTOP USERS@DOMAIN.LOCAL"` rather than just the name  

That being said, that specific error is regarding a new feature I was testing out, I've fixed it in the most recent commit, poor testing on my part. Thanks for the feedback!
